### ISSUE TITLE
The wallet address in the curl request response is truncated

### ISSUE THREAD

**Issue by Swericor** [graft-project/graft-ng#227]
When performing the curl request to receive the public identifier key, supernode public wallet address and signature from the supernode, the address is truncated by one digit.

The response is:
{"testnet":true,"wallet_public_address":"F9BcBsUbKNhSmJuKe3xnY1WMQWaViRFtvX4GYtNdUgWkAGPAVL7qbMb2NxX1xMmUeRgVtmf76dxESbpahf4utXEkSgqTCT","id_key":"ddac6273228c43939ee9203203f4d8ee6efa616410fb1b69e55924c9ac0d1e41","signature":"be8dc395a5f8cda78d8d1701ae5c3a4367028399ecb1d0f982699204f5ba2d004163a1ff8d6d7eac434c84741a7ef8506e300b993e25ea03fdf5396784702408"

While the actual address is:
F9BcBsUbKNhSmJuKe3xnY1WMQWaViRFtvX4GYtNdUgWkAGPAVL7qbMb2NxX1xMmUeRgVtmf76dxESbpahf4utXEkSgqTCTv

When performing the stake transaction the wallet gives an "invalid supernode signature" error, as expected.

The get request has been tested on local host and remote using curl, and in a web browser. The error is consistent in all cases.

**Comment by Swericor** [comment]
Turns out it was a simple error, the wallet address in the config.ini was incorrectly entered.

**Comment by bitkis** [comment]
thanks
