### ISSUE TITLE
Problems with compiling on Ubuntu 18.04

### ISSUE THREAD

**Issue by CryptoBilko** [graft-project/graft-ng#236]
Im getting this error while compiling:

[  1%] Building CXX object CMakeFiles/graftlet_lib.dir/src/lib/graft/GraftletLoader.cpp.o
In file included from /home/graft/graft-ng/include/lib/graft/GraftletLoader.h:23:0,
                 from /home/graft/graft-ng/src/lib/graft/GraftletLoader.cpp:26:
/home/graft/graft-ng/include/lib/graft/IGraftlet.h:10:15: fatal error: any: No such file or directory
compilation terminated.
CMakeFiles/graftlet_lib.dir/build.make:62: recipe for target 'CMakeFiles/graftlet_lib.dir/src/lib/graft/GraftletLoader.cpp.o' failed
make[2]: *** [CMakeFiles/graftlet_lib.dir/src/lib/graft/GraftletLoader.cpp.o] Error 1
CMakeFiles/Makefile2:225: recipe for target 'CMakeFiles/graftlet_lib.dir/all' failed
make[1]: *** [CMakeFiles/graftlet_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

The needed file is right there, i prooved it.
I use cmake version 3.13.3, could this be the cause of that problem, or is it a bug ?
Thanx for helping...

**Comment by AlexanderSuprunenko** [comment]
Hi, 
1. Could you give us 'gcc --version' ? I have 'gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0'
2. Could you place 
set(CMAKE_CXX_STANDARD_REQUIRED ON)
just after
set(CMAKE_CXX_STANDARD 17)
in CMakeLists.txt ?

**Comment by CryptoBilko** [comment]
gcc --version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
I placed it in the CMakeLists.txt:

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
 
same error again.

**Comment by AlexanderSuprunenko** [comment]
Thank you for the information. 

Please make sure you use gcc 7.3.0 .  I'll review our docs and ensure no misleading info is provided.

Please keep as updated on your progress.

**Comment by CryptoBilko** [comment]
Thanks for the quick help, mate, Thats one of the reasons, why i love graft :-)

When i do a fresh git clone, the installation runs fine until this: 

`>[ 19%] Performing configure step for 'cryptonode'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
==> The configuration is RelWithDebInfo. Debug info will be extracted into separate files.
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found version "1.0.2g")  
-- Found MiniUPnPc: /usr/include/miniupnpc  
-- Found miniupnpc API version 10
-- Using miniupnpc from local source tree for static build
-- Looking for libunbound
CMake Error at external/CMakeLists.txt:82 (add_subdirectory):
  The source directory

    /home/graft/graft-ng/modules/cryptonode/external/unbound

  does not contain a CMakeLists.txt file.


-- Using 64-bit LMDB from source tree
-- Building on x86_64 for native
-- AES support enabled
-- Found Boost Version: 106900
-- Found Readline: /usr/include  
-- Performing Test GNU_READLINE_FOUND
-- Performing Test GNU_READLINE_FOUND - Failed
-- Could not find GNU readline library so building without readline support
-- Found Git: /usr/bin/git
CMake Warning (dev) at CMakeLists.txt:63 (add_custom_command):
  Policy CMP0040 is not set: The target in the TARGET signature of
  add_custom_command() must exist and must be defined in the current
  directory.  Run "cmake --help-policy CMP0040" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  TARGET 'Doxygen::doxygen' is IMPORTED and does not build here.
Call Stack (most recent call first):
  /usr/local/lib/python3.5/dist-packages/cmake/data/share/cmake-3.13/Modules/FindDoxygen.cmake:439 (add_executable)
  /usr/local/lib/python3.5/dist-packages/cmake/data/share/cmake-3.13/Modules/FindDoxygen.cmake:592 (_Doxygen_find_doxygen)
  CMakeLists.txt:770 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:63 (add_custom_command):
  Policy CMP0040 is not set: The target in the TARGET signature of
  add_custom_command() must exist and must be defined in the current
  directory.  Run "cmake --help-policy CMP0040" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  TARGET 'Doxygen::dot' is IMPORTED and does not build here.
Call Stack (most recent call first):
  /usr/local/lib/python3.5/dist-packages/cmake/data/share/cmake-3.13/Modules/FindDoxygen.cmake:524 (add_executable)
  /usr/local/lib/python3.5/dist-packages/cmake/data/share/cmake-3.13/Modules/FindDoxygen.cmake:596 (_Doxygen_find_dot)
  CMakeLists.txt:770 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components:  doxygen dot 
-- Performing Test HAVE_C11
-- Performing Test HAVE_C11 - Success
-- Looking for memset_s in c
-- Looking for memset_s in c - not found
-- Looking for explicit_bzero in c
-- Looking for explicit_bzero in c - not found
-- Configuring incomplete, errors occurred!
See also "/home/graft/graft-ng/build/BUILD/cryptonode/CMakeFiles/CMakeOutput.log".
See also "/home/graft/graft-ng/build/BUILD/cryptonode/CMakeFiles/CMakeError.log".
CMakeFiles/cryptonode.dir/build.make:105: recipe for target 'STAMP/cryptonode/cryptonode-configure' failed
make[2]: *** [STAMP/cryptonode/cryptonode-configure] Error 1
CMakeFiles/Makefile2:149: recipe for target 'CMakeFiles/cryptonode.dir/all' failed
make[1]: *** [CMakeFiles/cryptonode.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by CryptoBilko** [comment]
When i try your precompiled binarys (v1.1.0) im getting this boost error:

./supernode: error while loading shared libraries: libboost_program_options.so.1.65.1: cannot open shared object file: No such file or directory

**Comment by Patrickdurbin** [comment]
> When i try your precompiled binarys (v1.1.0) im getting this boost error:
> ./supernode: error while loading shared libraries: libboost_program_options.so.1.65.1: cannot open shared object file: No such file or directory

sudo apt-get install libboost-all-dev

**Comment by tbakky** [comment]
> Thanks for the quick help, mate, thats one of the reasons, why i love graft :-)
> 
> When i do it on a fresh git clone, the process runs fine until this:
> 
...
> `
This is the same issue I ran into, if anyone else has this issue use this command:

git submodule update --init --recursive

instead of this one:

git submodule update --recursive

Making that change I was able to successfully build on Ubuntu 18.04

**Comment by CryptoBilko** [comment]
git submodule update --init --recursive

That was it, thanx a lot :-)
