### ISSUE TITLE
git submodule update command 

### ISSUE THREAD

**Issue by tbakky** [graft-project/graft-ng#237]
I just built the graft-ng project on a Ubuntu 18.04 system.  Using the suggested command:

git submodule update --recursive

from the root directory of the project does not work for me to recursively download all the modules.

What did work was:

git submodule update --init --recursive

Is this a system specific issue?  If it is a broader issue you might consider changing the installation guide.

**Comment by Patrickdurbin** [comment]
it also needs to tell you to manually include 1.66 boost. (msys64) for windows compilations.
     git clone --recurse-submodules https://github.com/graft-project/GraftNetwork
make release-static-win64

**Comment by ku4eto** [comment]
https://github.com/graft-project/graft-ng/pull/240

Issue has been resolved in PR #240 , README.md is updated . You can close the issue.
