### ISSUE TITLE
Pre-compiled Ubuntu 18.04 binaries do not work

### ISSUE THREAD

**Issue by ku4eto** [graft-project/graft-ng#251]
As the title says.

I have a VM on VirtualBox, running a Ubuntu 18.04.

The moment i try to start the ./supernode, it terminates with `Illegal instruction (core dumped)`.

Any ideas on that?

**Comment by Patrickdurbin** [comment]
Well It was never meant to be ran in a virtual machine. (The illegal instruction) is probably a virtualization issue. (although you could put a core dump up here) I doubt anyone will look into it. 

Are you on windows? 
Why not use WSL? (although that brings its on issues)

**Comment by dcutugno** [comment]
i have the same problem with native ubuntu machine core i3 2100, if you compile the supernode on the same machine it will run but binaries give error, please dev have a look

**Comment by ku4eto** [comment]
> 
> 
> Well It was never meant to be ran in a virtual machine. (The illegal instruction) is probably a virtualization issue. (although you could put a core dump up here) I doubt anyone will look into it.
> 
> Are you on windows?
> Why not use WSL? (although that brings its on issues)
> 
> Truth is 18.04 native should be the only place you would run it. (or equivalent kernel)

Your comment is a bit stupid, though.

A VPS is exactly that, a VM. Just with a different host OS and hypervisor. All of the example hostings are actually running Virtual Machines. You are literally talking about dedicated servers. And those cost a huge amount of money.

My host OS is Windows. the guest machine is Ubuntu. If i compile it manually, it works. Its the pre-compiled ones that do not work.

If additional flags need to be passed to the VM when starting up, or you devs the coredump, please say, i can provide dumps and attach extra flags to the headless VM.

**Comment by Patrickdurbin** [comment]
**There has been issues compiling graft-ng in general on certain rental VPS**

without extra CPU compilation flags disabling avx512 bit was an issue that led to core dumps as well on a certain VPS. I cant remember then name though. Vultr I believe.  They updated cmake as a fix.  

The illegal Instruction is coming about from the prebuilt binaries.  Probably a similar issue. 

The VPS and virtualization are the same. But for all I know your CPU did or dint have certain features turned off in virtualization and would result in a core dump. 

Where as most VPS are uniform for the most part on instruction sets on their x86 virtual CPU's that are provided. 

for all we know the precompiled binary's were compiled natively on debug.  This is the issue.  But running on a Virtual CPU within windows... (is limited on instruction sets in general) if you did not have the professional version for example. Or if you didn't have certain things setup in your System bios... 

For the most part VPS are pretty uniform. On instruction sets. Where as a day to day virtualization locally is not a good example to be submitting a core dump on illegal instruction.

**Comment by ku4eto** [comment]
Seems like you are right. Sorry.

I am with a i5-3570S, and this are the passed CPU flags via Virtualbox:

```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes xsave avx rdrand hypervisor lahf_lm pti fsgsbase flush_l1d
```

So, its either not a passed flag, or missing instruction set for older gen CPUs.

**Comment by Patrickdurbin** [comment]
Graft-ng binaries need to be built with the most simple cpu instruction set.

**Comment by ku4eto** [comment]
Closing, since the new v1.0.3 release has working pre-compiled binaries.
