### ISSUE TITLE
x86 virtulization (segmentation faults) 

### ISSUE THREAD

**Issue by Patrickdurbin** [graft-project/graft-ng#253]
As of now graft-ng has 2 issues ive seen.

Core Dumps from segmentation faults and from illegal instruction sets from prebuilt binarys.

I believe both are coming from the fact the code requires specific instruction sets that VPS don't have.  or that are being ignored in the compilation process that might be needed. 

This results in l2 or l3 cache not owned by the process asking ot be written to by an instruction set being virtulized and results in a segmentation fault.  (the same issue)  results in an illegal instruction if the cpu doesnt support the instruction set. 

When compiling you can compile non-natively meaning the code will run on most cpu's are any cpu's 
You also compile with debug  or  release  this optimizes code. 

There needs to be a massive amount of core dumps uploaded from people that are having them across the x86 virtualized cpu's and people need to specify what host they have when running it. 

As of now the segmentation faults I think are coming from the cache of the cpu due to instruction sets being expected.

**Comment by ku4eto** [comment]
Latest v1.0.3 pre-compiled binaries work for me. Previous did not.
